# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Announcement',
            field=models.CharField(default='\u65e0', max_length=100, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
