# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170514_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Announcement',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
