# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170525_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
