# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170425_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', '\u57f9\u8bad\u673a\u6784'), ('per', '\u4e2a\u4eba'), ('uni', '\u9ad8\u6821')], default='org', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='imgae',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
