# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170507_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='imgae',
            new_name='image',
        ),
    ]
