# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6559\u5e08\u5e74\u9f84'),
        ),
    ]
